# http or https
protocol="https"
# the domain or ip to use for returning image urls
# this should **not** include the protocol, and should not have a following slash
# example: example.com
domain = ""
# the port that the server should start on
port = 3100
# the ip to run the server behind
# NOTE: It's better to leave this as 127.0.0.1 and put a proxy in front of the application and rewrite to 127.0.0.1:3000
ip = "127.0.0.1"
# the max image size to allow in kilobytes
max_image_size = 10240
# the max iamge size to allow in kilobytes
max_audio_size = 20480
